---
ansible_code_path: "{{ ansible_env.HOME }}/Code/ansible"

local_bin: "{{ ansible_env.HOME }}/.local/bin"

local_share: "{{ ansible_env.HOME }}/.local/share"

code_path: "{{ ansible_env.HOME }}/Code"

key_file: "{{ ansible_env.HOME }}/.ssh/workstation_rsa"

source_path: "{{ code_path }}/sources"

config_path: "{{ ansible_env.HOME }}/.config"

neovim_source_path: "{{ source_path }}/neovim"
